---
- name: Get Vector distrib archive
  ansible.builtin.get_url:
    url: https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-gnu.tar.gz
    dest: ./vector.tar.gz
    mode: '0655'
- name: Unarchive distrib
  ansible.builtin.unarchive:
    src: ./vector.tar.gz
    dest: ./
    remote_src: true
- name: Create Vector install directory
  become: true
  ansible.builtin.file:
    path: "{{ vector_install_dir }}"
    state: directory
    mode: '0755'
- name: Move Vector binary
  become: true
  ansible.builtin.copy:
    src: "./vector-x86_64-unknown-linux-gnu/bin/vector"
    dest: "{{ vector_install_dir }}/vector"
    mode: '0755'
    remote_src: true
- name: Create Vector config directory
  become: true
  ansible.builtin.file:
    path: "{{ vector_config_dir }}"
    state: directory
    mode: '0755'
- name: Copy Vector configuration
  become: true
  ansible.builtin.template:
    src: templates/vector/vector.toml.j2
    dest: "{{ vector_config_dir }}/vector.yaml"
    mode: '0644'
- name: Create Vector service file
  become: true
  ansible.builtin.template:
    src: templates/vector/vector.service.j2
    dest: /etc/systemd/system/vector.service
    mode: '0644'
- name: Create Vector data directory
  become: true
  ansible.builtin.file:
    path: "{{ vector_data_dir }}"
    state: directory
    mode: '0755'
- name: Enable Vector service
  become: true
  ansible.builtin.service:
    name: vector
    daemon_reload: true
    enabled: true
  notify:
    - Start vector service
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
